proc_trees:
  - name: far_buoys
    proc_units:
      - name: blur
        blur_type: 1
        debug: false
      - name: threshold
        threshold_type: 0
        debug: false
      - name: morphology
        debug: false
      - name: wall_remover
        debug: false
      - name: blob_detector
        target: 1
        debug: true
      - name: far_buoys_detector
  - name: buoys
    proc_units:
      - name: blur
        blur_type: 1
        debug: false
      - name: threshold
        threshold_type: 0
        debug: false
      - name: morphology
        debug: false
#      - name: wall_remover
#        debug: false
      - name: blob_detector
        target: 0
        debug: true
      - name: buoys_detector
        roi : false
#  - name: fence
#    proc_units:
#      - name: blur
#        blur_type: 1
#        debug: false
#      - name: threshold
#        threshold_type: 0
#        debug: false
#      - name: dilate
#        debug: false
#      - name: blob_detector
#        target: 0
#        debug: false
  - name: wall
    proc_units:
      - name: blur
        blur_type: 1
        debug: true
      - name: morphology
        debug: false
      - name: threshold
        threshold_type: 0
        debug: true

# Comment this line in order to have no default proc tree
default: "buoys"
