proc_trees:
  - name: far_buoys
    proc_units:
      - name: blur
        blur_type: 1
        kernel_size: 3
        debug: false
      - name: threshold
        threshold_type: 0
        thresh_value: 10
        debug: false
      - name: morphology
        kernel_size_x: 4
        kernel_size_y: 4
        debug: false
      - name: wall_remover
        debug: false
      - name: blob_detector
        target: 1
        debug: false
      - name: far_buoys_detector
  - name: buoys
    proc_units:
      - name: blur
        blur_type: 1
        kernel_size: 3
        debug: true
      - name: threshold
        threshold_type: 0
        thresh_value: 10
        debug: true
      - name: morphology
        kernel_size_x: 4
        kernel_size_y: 4
        debug: false
      - name: wall_remover
        debug: false
      - name: blob_detector
        target: 0
        debug: true
      - name: buoys_detector
        roi : false
  - name: fence
    proc_units:
      - name: blur
        blur_type: 1
        kernel_size: 3
        debug: false
      - name: threshold
        threshold_type: 0
        thresh_value: 10
        debug: false
      - name: morphology
        kernel_size_x: 4
        kernel_size_y: 4
        debug: false
      - name: wall_remover
        debug: false
      - name: blob_detector
        target: 1
        debug: false
      - name: fence_detector
  - name: wall
    proc_units:
      - name: blur
        blur_type: 1
        kernel_size: 3
        debug: false
      - name: morphology
        kernel_size_x: 4
        kernel_size_y: 4
        debug: false
      - name: threshold
        threshold_type: 0
        thresh_value: 10
        debug: false

# Comment this line in order to have no default proc tree
default: "buoys"
