proc_trees:
  - name: far_buoys
    proc_units:
      - name: histogram
      - name: blur
        blur_type: 1
        kernel_size: 3
      - name: threshold
        threshold_type: 0
        thresh_value: 20
      - name: morphology
        kernel_size_x: 4
        kernel_size_y: 4
      - name: wall_remover
        area_size: 90
        width_size: 80
      - name: blob_detector
        min_threshold: 200
        max_threshold: 255
        filter_by_area: true
        min_area: 8
        max_area: 24
        filter_by_color: false
        blob_color: 255
        filter_by_circularity: false
        min_circularity: 1
        max_circularity: 2
        filter_by_convexity: false
        min_convexity: 1
        max_convexity: 2
        filter_by_inertia: false
        min_inertia: 1
        max_inertia: 2
      - name: far_buoys_detector
        roi_needed: true
        weight_goal: 5
  - name: buoys
    proc_units:
      - name: blur
        blur_type: 1
        kernel_size: 3
      - name: threshold
        threshold_type: 0
        thresh_value: 35
      - name: morphology
        kernel_size_x: 4
        kernel_size_y: 4
      - name: wall_remover
        area_size: 70
        width_size: 80
      - name: blob_detector
        min_threshold: 30
        max_threshold: 200
        filter_by_area: true
        min_area: 10
        max_area: 65
        filter_by_color: true
        blob_color: 255
        filter_by_circularity: false
        min_circularity: 1
        max_circularity: 2
        filter_by_convexity: false
        min_convexity: 1
        max_convexity: 2
        filter_by_inertia: false
        min_inertia: 1
        max_inertia: 2
      - name: far_buoys_detector
        roi_needed: false
        weight_goal: 10
  - name: fence
    proc_units:
      - name: blur
        blur_type: 1
        kernel_size: 3
      - name: threshold
        threshold_type: 0
        thresh_value: 10
      - name: morphology
        kernel_size_x: 4
        kernel_size_y: 4
      - name: wall_remover
        area_size: 50
        width_size: 50
      - name: blob_detector
        min_threshold: 200
        max_threshold: 255
        filter_by_area: true
        min_area: 5
        max_area: 30
        filter_by_color: false
        blob_color: 255
        filter_by_circularity: false
        min_circularity: 1
        max_circularity: 2
        filter_by_convexity: false
        min_convexity: 1
        max_convexity: 2
        filter_by_inertia: false
        min_inertia: 1
        max_inertia: 2
      - name: fence_detector
        roi_needed: true
        weight_goal: 5

# Comment this line in order to have no default proc tree
default: "buoys"
