regions_of_interest:
  - objecy_type: buoys
    roi_type: rotated_rectangle
    name: BUOY_ROI
    center:
      - [10, 10]
    size:
      - [1, 1]
    angle: 135
  - objecy_type: fence
    roi_type: contour
    name: FENCE_ROI
    points:
      - [1, 10] #Top left
      - [3, 6] #Top right
      - [6, 3] #Bottom right
      - [1, 2] #Bottom left